# Generated by Django 4.2.1 on 2023-05-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_adhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_adhar',
            name='adhar_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer_adhar',
            name='adhar_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
